LinuxPermissionSimulator/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include("login.urls"), name='index'),
    path('manager/', include("manager.urls"), name='manager'),
    path('admin/', admin.site.urls),
]

login/urls.py
from django.urls import path

from . import views

app_name = "login"
urlpatterns = [
    path("", views.index, name="index"),
    path("check/", views.check, name="check"),
]

manager/urls.py
from django.urls import path

from . import views

app_name = "manager"
urlpatterns = [
    path("", views.manager, name="manager"),
    path("read/", views.read, name="read"),
    path("write/", views.write, name="write"),
    path("execute/", views.execute, name="execute"),
    path("add/", views.add, name="add"),
]

login/models.py
from django.db import models

# Create your models here.

manager/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User, Group


class File(models.Model):
    # 文件名
    name = models.CharField(max_length=255)

    # 文件属主（外键关联到User模型）
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owned_files')

    # 文件属组（外键关联到Group模型）
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='group_files')

    # 权限位（整数字段）
    # 假设我们使用一个3位的整数来表示权限，每位代表读、写、执行权限
    # 例如，7代表读、写、执行都有，6代表读、写权限，4代表只读权限
    permissions = models.IntegerField()

login/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth import authenticate, login


# Create your views here.

def index(request):
    return render(
        request,
        "login/login.html",
    )


def check(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = redirect("manager:manager")
            response.set_cookie("username", username, max_age=3600)
            return response
        else:
            return render(
                request,
                "login/login.html",
                {
                    "error_message": "请检查用户名或者密码",
                },
            )

    if request.method == 'GET':
        return render(
            request,
            "login/login.html",
            {
                "error_message": "请输入用户名或者密码",
            },
        )

manager/views.py
import json
from urllib import request

from django.contrib.auth.models import User, Group
from django.http import HttpResponse
from django.shortcuts import render
from .models import File


# Create your views here.

def manager(request):
    file_list = get_file_list()
    for file in file_list:
        file['permissions'] = permissions_to_string(file['permissions'])
    return render(
        request,
        "manager/manager.html",
        {
            "file_list": file_list,
        },
    )


def read(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        num = int(data.get('num'))
        file_list = get_file_list()
        file = file_list[num]
        owner = file.get('owner')
        group = file.get('group')
        permissions = file.get('permissions')
        permissions = permissions_to_string(permissions)
        username = request.COOKIES.get('username')
        user = User.objects.get(username=username)  # 获取用户
        if owner == user.__str__():
            if permissions[0] == "r":
                return HttpResponse(json.dumps({"status": "read_success"}))
            else:
                return HttpResponse(json.dumps({"status": "read_failed"}))
        elif is_user_in_group(user, group):
            if permissions[3] == "r":
                return HttpResponse(json.dumps({"status": "read_success"}))
            else:
                return HttpResponse(json.dumps({"status": "read_failed"}))
        else:
            if permissions[6] == "r":
                return HttpResponse(json.dumps({"status": "read_success"}))
            else:
                return HttpResponse(json.dumps({"status": "read_failed"}))


def write(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        num = int(data.get('num'))
        file_list = get_file_list()
        file = file_list[num]
        owner = file.get('owner')
        group = file.get('group')
        permissions = file.get('permissions')
        permissions = permissions_to_string(permissions)
        username = request.COOKIES.get('username')
        user = User.objects.get(username=username)  # 获取用户
        if owner == user.__str__():
            if permissions[1] == "w":
                return HttpResponse(json.dumps({"status": "write_success"}))
            else:
                return HttpResponse(json.dumps({"status": "write_failed"}))
        elif is_user_in_group(user, group):
            if permissions[4] == "w":
                return HttpResponse(json.dumps({"status": "write_success"}))
            else:
                return HttpResponse(json.dumps({"status": "write_failed"}))
        else:
            if permissions[7] == "w":
                return HttpResponse(json.dumps({"status": "write_success"}))
            else:
                return HttpResponse(json.dumps({"status": "write_failed"}))


def execute(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        num = int(data.get('num'))
        file_list = get_file_list()
        file = file_list[num]
        owner = file.get('owner')
        group = file.get('group')
        permissions = file.get('permissions')
        permissions = permissions_to_string(permissions)
        username = request.COOKIES.get('username')
        user = User.objects.get(username=username)  # 获取用户
        if owner == user.__str__():
            if permissions[2] == "x":
                return HttpResponse(json.dumps({"status": "execute_success"}))
            else:
                print(permissions)
                return HttpResponse(json.dumps({"status": "execute_failed"}))
        elif is_user_in_group(user, group):
            if permissions[5] == "x":
                return HttpResponse(json.dumps({"status": "execute_success"}))
            else:
                return HttpResponse(json.dumps({"status": "execute_failed"}))
        else:
            if permissions[8] == "x":
                return HttpResponse(json.dumps({"status": "execute_success"}))
            else:
                return HttpResponse(json.dumps({"status": "execute_failed"}))


def add(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        file_name = data.get('file_name')
        permissions = data.get('permissions')
        owner = request.COOKIES.get('username')
        user = User.objects.get(username=owner)
        groups = user.groups.all()
        group = groups[0]
        print('add')
        new_file = File(name=file_name, owner=user, group=group, permissions=permissions)
        new_file.save()
        return HttpResponse(json.dumps({"status": "add_success"}))
    else:
        return HttpResponse(json.dumps({"status": "add_failed"}))


def get_file_list():
    all_files = File.objects.all()
    file_list = []
    for file in all_files:
        print(file.name)
        file_info = {
            "name": file.name,
            "permissions": file.permissions,
            "owner": file.owner.username,
            "group": file.group.name,
        }
        file_list.append(file_info)
    return file_list


def is_user_in_group(user, group_name):
    """
    判断用户是否在指定的组中。

    参数:
    - user: User 实例
    - group_name: 要检查的组的名字

    返回值:
    - 如果用户在指定的组中，返回 True
    - 否则，返回 False
    """
    return user.groups.filter(name=group_name).exists()


def permissions_to_string(permissions):
    # 将整数权限拆分为三位
    permissions_str = str(permissions).zfill(3)

    # 定义权限字典
    permissions_dict = {'1': '--x', '2': '-w-', '3': '-wx', '4': 'r--', '5': 'r-x', '6': 'rw-', '7': 'rwx', '0': '---'}

    # 使用列表推导来创建权限字符串
    permissions_string = ''.join([permissions_dict[char] for char in permissions_str])

    return permissions_string

templates/login/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="author" content="Kodinger">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title>My Login Page</title>
	<link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'login/css/my-login.css' %}">
</head>

<body class="my-login-page">
	<section class="h-100">
		<div class="container h-100">
			<div class="row justify-content-md-center h-100">
				<div class="card-wrapper">
					<div class="brand">
						<img src="{% static 'login/img/logo.jpg' %}" alt="logo">
					</div>
					<div class="card fat">
						<div class="card-body">
							<h4 class="card-title">登录</h4>
                            {% if error_message %}
                                <p class="text-danger"><strong>{{ error_message }}</strong></p>
                            {% endif %}
							<form action="{% url 'login:check' %}" method="POST" class="my-login-validation" novalidate="">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="phoneNum">用户名</label>
                                    <input id="phoneNum" type="text" class="form-control" name="username" value="" required autofocus>
                                    <div class="invalid-feedback">
                                        请输入用户名
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="ipAddress">密码</label>
                                    <input id="ipAddress" type="password" class="form-control" name="password" value="" required autofocus>
                                    <div class="invalid-feedback">
                                        请输入密码
                                    </div>
                                </div>

                                <div class="form-group m-0">
                                    <button type="submit" class="btn btn-primary btn-block">
                                    Login
                                    </button>
                                </div>
                            </form>
						</div>
					</div>
					<div class="footer">
						<p>&copy; 2023 &mdash;by onlyLTY</p>
					</div>
				</div>
			</div>
		</div>
	</section>
</body>
</html>

templates/manager/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_region %}

    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}">
    {% csrf_token %}
</head>
<body>
    <div class="layui-layout layui-layout-admin">
        <div class="layui-header">
            <!-- 头部区域（可配合layui 已有的水平导航） -->
            <div class="layui-logo">Linux访问控制机制模拟</div>
        </div>

        <div class="layui-side layui-bg-black">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree" lay-filter="test">
                    <li class="layui-nav-item layui-this"><a href="javascript:">文件</a></li>
{#                    <li class="layui-nav-item"><a href="javascript:">用户</a></li>#}
                </ul>
            </div>
        </div>

        <div class="layui-body" style="padding-left: 5px;">
            <!-- 内容主体区域 -->
            <div class="layui-row">
                <div class="layui-col-md12" style="padding: 5px;">
                    <!-- 按键区域 -->
                    {% block button_region %}{% endblock %}
                </div>
                <hr>
                {% block data_region %}

                {% endblock %}
            </div>
        </div>

        <div class="layui-footer">
            <!-- 底部固定区域 -->
            <div class="layui-col-lg-offset11">
                <!-- 底部数据显示 -->
                {% block footer_region %}

                {% endblock %}
            </div>
        </div>
    </div>

{% block scripts %}

{% endblock %}
</body>
</html>

templates/manager/manager.html
{% extends 'manager/base.html' %}
{% load static %}

{% block head_region %}
    <title>linux文件管理模拟</title>
{% endblock %}

{% block button_region %}
    <button id="read" type="button" class="layui-btn layui-btn-sm layui-btn-normal">请求读</button>
    <button id="write" type="button" class="layui-btn layui-btn-sm layui-btn-normal">请求写</button>
    <button id="execute" type="button" class="layui-btn layui-btn-sm layui-btn-normal">请求执行</button>
    <button id="add_file" type="button" class="layui-btn layui-btn-sm layui-btn-normal">添加文件</button>
{% endblock %}

{#{% block data_region %}#}
{#    <table class="layui-hide" id="container_table" lay-filter="container_table"></table>#}
{#{% endblock %}#}

{% block data_region %}
    <table class="layui-table" id="container_table" lay-skin="line" lay-data="{limit: Number.MAX_VALUE, id:'container_table'}" lay-filter="container_table">
        <colgroup>
            <col style="width: 70px">
        </colgroup>

        <thead>
        <tr>
            <th lay-data="{field:'file_name'}">文件名</th>
            <th lay-data="{field:'permissions'}">权限</th>
            <th lay-data="{field:'owner'}">属主</th>
            <th lay-data="{field:'group'}">属组</th>
        </tr>
        </thead>
        <tbody>
        {% if file_list %}
            {% for file in file_list %}
                <tr>
                    <td>{{ file.name }}</td>
                    <td>{{ file.permissions }}</td>
                    <td>{{ file.owner }}</td>
                    <td>{{ file.group }}</td>
                </tr>
            {% endfor %}
        {% else %}
            <p>列表为空</p>
        {% endif %}
        </tbody>
    </table>
{% endblock %}

{% block footer_region %}
    <span> <span id="rowCountDisplay"></span> 个文件</span>
{% endblock %}

{% block scripts %}
    <script src="{% static 'layui/layui.js' %}"></script>
    <!-- 具体的 JavaScript 代码 -->

    <script>
        layui.use('table', function(){
            var table = layui.table;
            //监听行单击事件（双击事件为：rowDouble）
            table.on('row(container_table)', function(obj){
            //标注选中样式
            obj.tr.addClass('layui-bg-blue active').siblings().removeClass('layui-bg-blue active');
          });
        });
    </script>

    <script>
        var read_button = document.getElementById('read');
        read_button.onclick = function () {
            var activeElements = document.getElementsByClassName("layui-bg-blue active");
            num = activeElements[0].getAttribute("data-index");
            read(num)
                .then(() => {
                    delayedReload();
                })
                .catch((error) => {
                    console.error("An error occurred:", error);
                });
        }

        var write_button = document.getElementById('write');
        write_button.onclick = function () {
            var activeElements = document.getElementsByClassName("layui-bg-blue active");
            num = activeElements[0].getAttribute("data-index");
            write(num)
                .then(() => {
                    delayedReload();
                })
                .catch((error) => {
                    console.error("An error occurred:", error);
                });
        }

        var execute_button = document.getElementById('execute');
        execute_button.onclick = function () {
            var activeElements = document.getElementsByClassName("layui-bg-blue active");
            num = activeElements[0].getAttribute("data-index");
            execute(num)
                .then(() => {
                    delayedReload();
                })
                .catch((error) => {
                    console.error("An error occurred:", error);
                });
        }

        var add_file_button = document.getElementById('add_file');
        add_file_button.onclick = function () {
            layer.prompt({title: '请输入文件名', formType: 0}, function(file_name, index){
                layer.close(index);
                layer.prompt({title: '请输入权限', formType: 0}, function(permissions, index){
                    layer.close(index);
                    add_file(file_name, permissions)
                        .then(() => {
                            delayedReload();
                        })
                        .catch((error) => {
                            console.error("An error occurred:", error);
                        });
                });
            });

        }

        function read(num) {
            return new Promise((resolve, reject) => {
                var csrftoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
                var xhr = new XMLHttpRequest();
                var url = "read/";
                var method = "POST";
                xhr.open(method, url, true);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                var data = {num: num}
                var params = JSON.stringify(data);
                xhr.onreadystatechange = function() {
                    if (xhr.readyState === 4) {
                        try {
                            var response = JSON.parse(xhr.responseText);
                            console.log(response);
                            if (response['status'] === 'read_success'){
                                layer.msg('您有读取权限',{time: 0});
                                resolve();
                            }else if (response['status'] === 'read_failed'){
                                layer.alert('权限不足', {icon: 5});
                                reject();
                            }
                        } catch (error) {
                            console.error("Failed to parse JSON response:", error);
                            layer.alert('请联系开发者', {icon: 5});
                        }
                    }
                };
                layer.msg('正在请求读取权限', {icon: 16, shade: 0.01});
                xhr.send(params);
            });
        }

        function write(num) {
            return new Promise((resolve, reject) => {
                var csrftoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
                var xhr = new XMLHttpRequest();
                var url = "write/";
                var method = "POST";
                xhr.open(method, url, true);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                var data = {num: num}
                var params = JSON.stringify(data);
                xhr.onreadystatechange = function() {
                    if (xhr.readyState === 4) {
                        try {
                            var response = JSON.parse(xhr.responseText);
                            console.log(response);
                            if (response['status'] === 'write_success'){
                                layer.msg('您有写入权限',{time: 0});
                                resolve();
                            }else if (response['status'] === 'write_failed'){
                                layer.alert('权限不足', {icon: 5});
                                reject();
                            }
                        } catch (error) {
                            console.error("Failed to parse JSON response:", error);
                            layer.alert('请联系开发者', {icon: 5});
                        }
                    }
                };
                layer.msg('请求写入',{time: 0});
                xhr.send(params);
            });
        }

        function execute(num) {
            return new Promise((resolve, reject) => {
                var csrftoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
                var xhr = new XMLHttpRequest();
                var url = "execute/";
                var method = "POST";
                xhr.open(method, url, true);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                var data = {num: num}
                var params = JSON.stringify(data);
                xhr.onreadystatechange = function() {
                    if (xhr.readyState === 4) {
                        try {
                            var response = JSON.parse(xhr.responseText);
                            console.log(response);
                            if (response['status'] === 'execute_success'){
                                layer.msg('您有执行权限',{time: 0});
                                resolve();
                            }else if (response['status'] === 'execute_failed'){
                                layer.alert('权限不足', {icon: 5});
                                reject();
                            }
                        } catch (error) {
                            console.error("Failed to parse JSON response:", error);
                            layer.alert('请联系开发者', {icon: 5});
                        }
                    }
                };
                layer.msg('请求执行',{time: 0});
                setTimeout(function() {
                    xhr.send(params);
                }, 1000);
            });
        }

        function add_file(file_name, permissions) {
            return new Promise((resolve, reject) => {
                var csrftoken = document.getElementsByName("csrfmiddlewaretoken")[0].value;
                var xhr = new XMLHttpRequest();
                var url = "add/";
                var method = "POST";
                xhr.open(method, url, true);
                xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
                var data = {file_name: file_name, permissions: permissions};
                var params = JSON.stringify(data);
                xhr.onreadystatechange = function() {
                    if (xhr.readyState === 4) {
                        try {
                            var response = JSON.parse(xhr.responseText);
                            console.log(response);
                            if (response['status'] === 'add_success'){
                                layer.msg('添加成功',{time: 0});
                                resolve();
                            }else if (response['status'] === 'add_failed'){
                                layer.alert('添加失败', {icon: 5});
                                reject();
                            }
                        } catch (error) {
                            console.error("Failed to parse JSON response:", error);
                            layer.alert('请联系开发者', {icon: 5});
                        }
                    }
                };
                layer.msg('正在添加文件',{time: 0});
                setTimeout(function() {
                   xhr.send(params);
                }, 1500); // 暂缓3秒执行xhr.send(params)
                });
        }

        function delayedReload() {
            setTimeout(function() {
                location.reload();
            }, 2500); // 延迟3秒钟（或3000毫秒）
        }
    </script>

    <script>
        const table = document.getElementById('container_table');
        const rowCount = table.getElementsByTagName('tbody')[0].getElementsByTagName('tr').length;
        document.getElementById('rowCountDisplay').innerText = rowCount;
    </script>
{% endblock %}